version: '3'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
  user-microservice-v1:
    build: ./user-microservice-v1
    ports:
      - "5001:5001"
  user-microservice-v2:
    build: ./user-microservice-v2
    ports:
      - "5003:5003"
  order-microservice:
    build: ./order-microservice
    ports:
      - "5002:5002"
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
